### ISSUE TITLE
Error on 1.16 pre10 (dependencies)

### ISSUE THREAD

**Issue by Aledark789** [DArkHekRoMaNT/ExtraOverlays#1]
18.12.2021 17:20:28 [Error] [extraoverlays] Could not resolve some dependencies:
18.12.2021 17:20:28 [Error] [extraoverlays]     game@1.16.0-pre.8 - Version mismatch (has 1.15.10)

**Comment by DArkHekRoMaNT** [comment]
Checked for 1.16.0-pre.10 and it works. Log looks like you are launching the mod on 1.15.10 o.O
