### ISSUE TITLE
Client crash if included in server

### ISSUE THREAD

**Issue by Hebgbs** [DArkHekRoMaNT/ExtraOverlays#2]
### Mod Version

1.3.1

### Game Version

1.18.1

### OS

Windows, Linux

### Play mode

Multiplayer

### Problem

CommonLib panics and causes game to fatal if Extra Overlays is included in a server's mod directory when remote machine _without_ Extra Overlays joins _even if_ CommonLib and other CommonLib-dependent mods exist in a known-working instance for single-player.

Continuation of [this](https://github.com/DArkHekRoMaNT/CommonLib/issues/2).

**Comment by DArkHekRoMaNT** [comment]
Don't move this to ExtraOverlays, the problem is still probably in CommonLib. And it will add confusion

**Comment by Hebgbs** [comment]
But how though? The problem clearly feels like an issue with Extra Overlays because when I remove it from server I can join the server and not be immediately kicked from a crash. I have Player Corpse, Teleportation Network and Capture Animals, none of these crash the game as I had experienced in the original post. And CommonLib is functioning as intended for those mods.

Granted, it's not meant to be in a server, as shown in ModDB being client-only. But I am looking at this from the viewpoint of an idiot who just bought a server and tossed their _everything_ into it. This mod shouldn't be crashing the game  if it's client-only because if it's on a server it should be plainly ignored, _right??_

**Comment by DArkHekRoMaNT** [comment]
Yes, but the game still loads code for any mods and doesn't unload the ones that are not needed. This way CommonLib can find config from unused mods. It now work in v2.1.1, the config system also make sure this mod is enabled and not just loaded.

**Comment by Hebgbs** [comment]
:+1:
