### ISSUE TITLE
IT doesn't work

### ISSUE THREAD

**Issue by Yombeaux** [DArkHekRoMaNT/ExtraOverlays#3]
I've installed the commons and it removed the error that prevented it from loading. It's not outright giving me any errors. But while I have it on in the list, nothing is happening when i hover my mouse over a creature.

**Comment by DArkHekRoMaNT** [comment]
There is a template for Bug Reports...

Game version?
Mod and CommonLib versions?
Single/Multiplayer?
What is in client-main.txt from %AppData%/VintagestoryData/Logs ?

**Comment by Yombeaux** [comment]
Sorry, I didn't know there was any kind of template.
Game version - 1.87.7
Mod and CommonLib versions - Mod version 1.3.1 CommonLib version 2.2.0
Single/Multiplayer - Multiplayer on paid server
What is in client-main.txt from %AppData%/VintagestoryData/Logs:
29.7.2023 17:08:15 [Notification] Client logger started.
29.7.2023 17:08:15 [Notification] Game Version: v1.18.7 (Stable)
29.7.2023 17:08:15 [Notification] Screens:
29.7.2023 17:08:15 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY1 (primary)
29.7.2023 17:08:15 [Notification] 1: {X=-1920,Y=0,Width=1920,Height=1080}, \\.\DISPLAY2 
29.7.2023 17:08:16 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
29.7.2023 17:08:16 [Notification] CPU Cores: 12
29.7.2023 17:08:16 [Notification] Available RAM: 32768 MB
29.7.2023 17:08:16 [Notification] Graphics Card Vendor: NVIDIA Corporation
29.7.2023 17:08:16 [Notification] Graphics Card Version: 3.3.0 NVIDIA 536.67
29.7.2023 17:08:16 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
29.7.2023 17:08:16 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
29.7.2023 17:08:16 [Notification] GL.MaxVertexUniformComponents: 4096
29.7.2023 17:08:16 [Notification] GL.MaxUniformBlockSize: 65536
29.7.2023 17:08:16 [Notification] Cairo Graphics Version: 1.17.3
29.7.2023 17:08:16 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
29.7.2023 17:08:16 [Notification] C# Framework: .net Framework 4.0.30319.42000
29.7.2023 17:08:16 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
29.7.2023 17:08:16 [Notification] Start discovering assets
29.7.2023 17:08:16 [Notification] Found 23 base assets in category lang
29.7.2023 17:08:16 [Notification] Found 0 base assets in category patches
29.7.2023 17:08:16 [Notification] Found 22 base assets in category config
29.7.2023 17:08:16 [Notification] Found 0 base assets in category worldproperties
29.7.2023 17:08:16 [Notification] Found 46 base assets in category sounds
29.7.2023 17:08:16 [Notification] Found 97 base assets in category shapes
29.7.2023 17:08:16 [Notification] Found 72 base assets in category shaders
29.7.2023 17:08:16 [Notification] Found 16 base assets in category shaderincludes
29.7.2023 17:08:16 [Notification] Found 131 base assets in category textures
29.7.2023 17:08:16 [Notification] Found 4 base assets in category music
29.7.2023 17:08:16 [Notification] Found 0 base assets in category dialog
29.7.2023 17:08:16 [Notification] Found 411 base assets in total
29.7.2023 17:08:16 [Notification] Loading sounds
29.7.2023 17:08:16 [Notification] Sounds loaded
29.7.2023 17:08:16 [Notification] (Re-)loaded frame buffers
29.7.2023 17:08:16 [Notification] Loaded Shaderprogramm for render pass .
29.7.2023 17:08:16 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
29.7.2023 17:08:16 [Notification] (Re-)loaded frame buffers
29.7.2023 17:08:16 [Notification] Begin loading shaders
29.7.2023 17:08:16 [Notification] Load shaders now
29.7.2023 17:08:16 [Notification] Loading shaders...
29.7.2023 17:08:16 [Notification] Loaded Shaderprogramm for render pass standard.
29.7.2023 17:08:16 [Notification] Loaded Shaderprogramm for render pass particlescube.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass particlesquad.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass sky.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass nightsky.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass woittest.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass helditem.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass decals.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass final.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass gui.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass blur.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass findbright.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass godrays.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass autocamera.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass wireframe.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass entityanimated.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass luma.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass blit.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass texture2texture.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass celestialobject.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass colorgrade.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass guigear.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass ssao.
29.7.2023 17:08:17 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
29.7.2023 17:08:17 [Notification] Cached session key is valid, validating with server
29.7.2023 17:08:17 [Notification] Server validation response: Good
29.7.2023 17:08:17 [Notification] Will search the following paths for mods:
29.7.2023 17:08:17 [Notification]     E:\Games\Vintagestory\Mods
29.7.2023 17:08:17 [Notification]     C:\Users\Meagan\AppData\Roaming\VintagestoryData\Mods
29.7.2023 17:08:18 [Notification] [DeathWaypoints_v1.0.3.cs] Successfully compiled 1 source files
